const mongoose=require('mongoose')

let OrderSchema=new mongoose.Schema({
    oid:{
        type:String,
        required:true
    },
    orderData:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'OrderProduct'
        }
    ],OrderValue:{
        type:Number,
        required:true
    },
    billingAddress:{
        aid:{
            type:String,
            required:true
        },
        custName:{
            type:String,
            required:true,
            trim:true
        },
        HouseNo:{
            type:String,
            required:true,
            trim:true
        },
        locality:{
            type:String,
            trim:true,
            required:true
        },
        Pincode:{
            type:Number,
            required:true,
            trim:true
        },
        District:{
            type:String,
            required:true,
            trim:true
        },
        State:{
            type:String,
            required:true,
            required:true
        },
        Mobile:{
            type:Number,
            required:true,
            trim:true
        }
    },shippingAddress:{
        aid:{
            type:String,
            required:true
        },
        custName:{
            type:String,
            required:true,
            trim:true
        },
        HouseNo:{
            type:String,
            required:true,
            trim:true
        },
        locality:{
            type:String,
            trim:true,
            required:true
        },
        Pincode:{
            type:Number,
            required:true,
            trim:true
        },
        District:{
            type:String,
            required:true,
            trim:true
        },
        State:{
            type:String,
            required:true,
            required:true
        },
        Mobile:{
            type:Number,
            required:true,
            trim:true
        }
    },
    paymentStatus:{
        type:String,
        default:'incomplete'
    },paymentMode:{
        type:String,
    },
    deliveryStatus:{
        currentState:{
            type:String,
            trim:true
        },
    }
},{timestamps: true})

let orderModal=mongoose.model('Order',OrderSchema);

module.exports=orderModal;